package Pacman;

import org.newdawn.slick.Image;
import org.newdawn.slick.SlickException;

public class Images {
    public static Image modeNight;
    public static Image modeCity;
    public static Image modeSnow;
    public static Image modeHalloween;
    public static Image modeSummer;
    public static Image modeDefault;
    public static Image defaultMode;
    public static Image Play;
    public static Image background;
    public static Image choice;
    public static Image classic;
    public static Image timed;
    public static Image revenge;
    public static Image Help;
    public static Image SoundOff;
    public static Image SoundOn;
    public static Image ExitScreen;
    public static Image yes;
    public static Image no;
    public static Image b1;
    public static Image b2;
    public static Image b3;
    public static Image Menu;
    public static Image PlayButton;
    public static Image HelpButton;
    public static Image HighScoreButton;
    public static Image QuitButton;
    public static Image Mode;
    public static Image modeNightButton;
    public static Image modeCityButton;
    public static Image modeSummerButton;
    public static Image modeHalloweenButton;
    public static Image modeDefaultButton;
    public static Image modeSnowButton;
    public static Image ExitButtonForHelp;
    public static Image loser;
    public static Image winner;
    public static Image leftArrow;
    public static Image rightArrow;
    public static Image Help2;
    public static Image Help3;
    public static Image Help4;
    public static Image modeRevenge;

    public Images() throws SlickException {
        modeRevenge = new Image("res/Images/modeRevenge.png");
        Help2 = new Image("res/Images/Help2.png");
        Help3 = new Image("res/Images/Help3.png");
        Help4 = new Image("res/Images/Help4.png");
        leftArrow = new Image("res/Images/leftArrow.png");
        rightArrow = new Image("res/Images/rightArrow.png");
        modeNight = new Image("res/Images/modeNight.png");
        modeCity = new Image("res/Images/modeCity.png");
        modeSnow = new Image("res/Images/modeSnow.png");
        modeHalloween = new Image("res/Images/modeHalloween.png");
        modeSummer = new Image("res/Images/modeSummer.png");
        modeDefault = new Image("res/Images/modeDefault.png");
        defaultMode = new Image("res/Images/defaultMode.png");
        //Play = new Image("res/Images/Play.png");
        Help = new Image("res/Images/Help1.png");
        SoundOff = new Image("res/Images/SoundOffButton.png");
        SoundOn = new Image("res/Images/SoundOnButton.png");
        ExitButtonForHelp = new Image("res/Images/ExitButtonForHelp.png");
        choice = new Image("res/Images/choice.png");
        classic = new Image("res/Images/classicButton.png");
        timed = new Image("res/Images/timedButton.png");
        revenge = new Image("res/Images/revengeButton.png");
        ExitButtonForHelp = new Image("res/Images/ExitButtonForHelp.png");
        ExitScreen = new Image("res/Images/ExitScreen.png");
        yes = new Image("res/Images/ExitYesButton.png");
        no = new Image("res/Images/ExitNoButton.png");
        background = new Image("res/Images/modeSpace.png");
        loser = new Image("res/Images/looser.png");
        winner = new Image("res/Images/winner.png");
        b1 = new Image("res/Images/one.png");
        b2 = new Image("res/Images/two.png");
        b3 = new Image("res/Images/three.png");
        Menu = new Image("res/Images/Menu.png");
        PlayButton = new Image("res/Images/PlayButton.png");
        HelpButton = new Image("res/Images/HelpButton.png");
        HighScoreButton = new Image("res/Images/HighScoreButton.png");
        QuitButton = new Image("res/Images/QuitButton.png");
        Mode = new Image("res/Images/Mode.png");
        modeNightButton = new Image("res/Images/modeNightButton.png");
        modeCityButton = new Image("res/Images/modeCityButton.png");
        modeSummerButton = new Image("res/Images/modeSummerButton.png");
        modeHalloweenButton = new Image("res/Images/modeHalloweenButton.png");
        modeDefaultButton = new Image("res/Images/modeDefaultButton.png");
        modeSnowButton = new Image("res/Images/modeSnowButton.png");
        ExitButtonForHelp = new Image("res/Images/ExitButtonForHelp.png");
    }

}
